# Generated by Django 5.1 on 2024-09-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField()),
                ("STD", models.PositiveIntegerField()),
                ("roll_number", models.IntegerField()),
                ("section", models.CharField(max_length=3)),
                ("Mark", models.IntegerField()),
                ("grad", models.CharField(max_length=1)),
            ],
        ),
    ]
