# Generated by Django 5.1 on 2024-09-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Mark",
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name="student",
            name="STD",
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
