# Generated by Django 5.1 on 2024-09-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_mark_alter_student_std"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Mark",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="STD",
            field=models.PositiveIntegerField(),
        ),
    ]
