# Generated by Django 5.1 on 2024-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_alter_student_mark_alter_student_std"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="Name",
            field=models.CharField(max_length=30),
        ),
    ]
