# Generated by Django 5.1 on 2024-09-04 07:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_alter_student_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="STD",
        ),
    ]
