# Generated by Django 5.1 on 2024-09-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_remove_student_std"),
    ]

    operations = [
        migrations.CreateModel(
            name="personlinfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Relationship", models.CharField(max_length=50)),
                ("Name", models.CharField(max_length=20)),
                ("Age", models.IntegerField()),
            ],
        ),
    ]
