# Generated by Django 5.1 on 2024-09-05 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_personlinfo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personlinfo",
            old_name="Name",
            new_name="name",
        ),
        migrations.AddField(
            model_name="personlinfo",
            name="student",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
            preserve_default=False,
        ),
    ]
