# Generated by Django 5.1 on 2024-09-06 05:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0007_rename_name_personlinfo_name_personlinfo_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personlinfo",
            name="student",
        ),
    ]
